footprint: [[-0.5, -0.33], [-0.5, 0.33], [0.5, 0.33], [0.5, -0.33]]
footprint_padding: 0.01

robot_base_frame: base_link
update_frequency: 4.0
publish_frequency: 3.0
transform_tolerance: 0.5

resolution: 0.05

obstacle_range: 5.5
raytrace_range: 6.0

#layer definitions
static:
    map_topic: /map
    subscribe_to_updates: true

obstacles_laser:
    observation_sources: velodyne
    velodyne: {sensor_frame: velodyne, data_type: PointCloud2, topic: points, marking: true, clearing: true}
    realsense: {sensor_frame: camera_realsense_gazebo, data_type: PointCloud2, topic: realsense/depth/color/points, marking: true, clearing: true}


inflation:
    inflation_radius: 1.0
