bluetooth_teleop:
  teleop_twist_joy:
    axis_linear: 7
    scale_linear: 0.5
    scale_linear_turbo: 2.0
    axis_angular: 3
    scale_angular: 1.4
    enable_button: 4
    enable_turbo_button: 5
  joy_node: 
    deadzone: 0.1
    autorepeat_rate: 20